### ISSUE TITLE
You Tube Model: Further understanding of the sampling algorithm in sequence.py script inorder to optimize speed

### ISSUE THREAD

**Issue by Sade-KD** [massquantity/LibRecommender#11]
Kindly refer to :
```
def sample_item_with_tolerance(num, consumed_items, consumed_len, tolerance=5):
    assert num > tolerance
    sampled = []
    first_len = num - tolerance
    while len(sampled) < first_len:
        i = floor(random() * consumed_len)
        if consumed_items[i] not in sampled:
            sampled.append(consumed_items[i])
    for _ in range(tolerance):
        i = floor(random() * consumed_len)
        sampled.append(consumed_items[i])
    return sampled
```
Generally, the algorithm takes seconds to train and predict for a sample size of 30k.
However, I noticed that when I trained on different samples of the same size, the duration differed considerably. It would hang at 1% training and was completing the function sample_item_with_tolerance. Can you perhaps elaborate on why this could be occurring and how I can optimize this aspect?

As a result, it has a major impact on speed when I increase the dataset from approx. 20000 to 2 mil  unique users. I have now moved it to the cloud for training and runs on a Deep Learning AMI AWS p2.xlarge instance. However, its still at 0 % training for the passed 3 hours. Is this an expected observation?

![training](https://user-images.githubusercontent.com/42578613/95842725-2e909b00-0d47-11eb-8102-1eea38cac6ad.PNG)

To confirm that it is processing information, I have taken a snapshot of the console output which prints the variable i in the while loop and the for loop. However, it doesn't seem to come out of the while loop.
![i](https://user-images.githubusercontent.com/42578613/95860539-753ebf00-0d60-11eb-8570-d6b15ed89aa6.PNG)

For further analysis, kindly snapshot below:
![i2](https://user-images.githubusercontent.com/42578613/95861887-61945800-0d62-11eb-8387-2bf914d8bfab.PNG)

Rerun on a different sample set of the data.
![i3](https://user-images.githubusercontent.com/42578613/95862409-2cd4d080-0d63-11eb-9110-da1fa845085a.PNG)

**Comment by massquantity** [comment]
From the picture, I can see that num of items is only 52 ?  In this case, the sampling process will indeed become slow. Because the algorithm will insist sample different items and there is really not so much items to sample.   
I didn't expect this situation happen, so the only way to adjust this is changing the tolerance to 0 in the `user_interacted_seq` function (in the same file as `sample_item_with_tolerance`). 

```python
def user_interacted_seq(user_indices, item_indices, user_consumed, pad_index,
                        mode=None, num=None, user_consumed_set=None):
    batch_size = len(user_indices)
    batch_interacted = np.full((batch_size, num), pad_index, dtype=np.int32)
    batch_interacted_len = []
    for j, (u, i) in enumerate(zip(user_indices, item_indices)):
        consumed_items = user_consumed[u]
        consumed_len = len(consumed_items)
        consumed_set = user_consumed_set[u]
        # If i is a negative item, then random sample some items
        # from user's past interacted items.
        if i not in consumed_set:
            if consumed_len >= num:
                chosen_items = sample_item_with_tolerance(
                    num, consumed_items, consumed_len, 5)   ################ change 5 to 0  ############
                batch_interacted[j] = chosen_items
                batch_interacted_len.append(float(num))
            else:
                batch_interacted[j, :consumed_len] = consumed_items
                batch_interacted_len.append(float(consumed_len))
        else:
            position = consumed_items.index(i)
            if position == 0:
                # first item, no historical interaction,
                # assign to pad_index by default, and length is 1.
                batch_interacted_len.append(1.0)
            elif position < num:
                batch_interacted[j, :position] = consumed_items[:position]
                batch_interacted_len.append(float(position))
            elif position >= num and mode == "recent":
                start_index = position - num
                batch_interacted[j] = consumed_items[start_index: position]
                batch_interacted_len.append(float(num))
            elif position >= num and mode == "random":
                chosen_items = np.random.choice(consumed_items, num,
                                                replace=False)
                batch_interacted[j] = chosen_items
                batch_interacted_len.append(float(num))

    return batch_interacted, batch_interacted_len


```

**Comment by Sade-KD** [comment]
Yes :)  In this data set, a client only has 52 item options and that's their maximum. I am testing it out and I will give update shortly.

**Comment by massquantity** [comment]
Sorry I made a mistake. In your case, you should actually increase tolerance to allow sampling duplicate items.
But I suggest you chnage the function directly:
```python
def sample_item_with_tolerance(num, consumed_items, consumed_len, tolerance=5):
    for _ in range(num):
        i = floor(random() * consumed_len)
        sampled.append(consumed_items[i])
    return sampled


```

**Comment by Sade-KD** [comment]
> ```python
> def sample_item_with_tolerance(num, consumed_items, consumed_len, tolerance=5):
>     for _ in range(num):
>         i = floor(random() * consumed_len)
>         sampled.append(consumed_items[i])
>     return sampled
> ```

Works much better! I updated as shown below:
def sample_item_with_tolerance(num, consumed_items, consumed_len, tolerance=5):
    sampled = []
    for _ in range(num):
        i = floor(random() * consumed_len)
        sampled.append(consumed_items[i])
    return sampled

I have not changed user_interacted_seq function.

Dataset of 30k/80k unique clients completed in seconds. For 2,5million -> training is in progress. 
![trainingall](https://user-images.githubusercontent.com/42578613/95873334-1d0fb900-0d70-11eb-9699-ce9722e469b9.PNG)

I will keep this opened until training completes successfully.
