### ISSUE TITLE
why youtube_retrieval usr_emb is fixed during serving

### ISSUE THREAD

**Issue by kinghuin** [massquantity/LibRecommender#111]
https://github.com/massquantity/LibRecommender/blob/master/libreco/algorithms/youtube_retrieval.py#L358

> Vector-based model relies on the dot product of two vectors to make recommendation, so we only need to save a bunch of vectors. This kind of model includes SVD, SVD++, ALS, BPR and YouTuBeRetrieval.

If YouTuBeRetrieval is a Vector-based model, its user embedding will not change during serving. But according to the paper,  it should calculate the latest user_last_interacted online in real time.

**Comment by massquantity** [comment]
Yeah you're right and someone has expressed similar concern in a [previous issue](https://github.com/massquantity/LibRecommender/issues/82#issuecomment-1040359324).

**Comment by kinghuin** [comment]
Thanks for your reply and look forward to this problem being solved.
