### ISSUE TITLE
Results interpretation

### ISSUE THREAD

**Issue by sunithak** [massquantity/LibRecommender#118]
I have tried running the autoint and svd++ on movielens data that you provided. The results are not very good. The recommendations makes no sense. No user collaboration, items also not very similar. I have tried youtube ranking also with merged dataset. Genres are also very different from each other. What is the base for kpi. Which algorithm can i use to run real time data from your collection.

**Comment by massquantity** [comment]
The example data only has 100 thousand rows, which is far from enough to train a good model. 
Besides, are you implying that a "sensible" recommendation is items with similar genres? And what kind of real time data you want to use?
