### ISSUE TITLE
How can we extract user Embeddings and use them directly in tf serving instead of indices for DeepFM? 

### ISSUE THREAD

**Issue by tanmaygovil1999-sharechat** [massquantity/LibRecommender#123]

**Comment by massquantity** [comment]
u want to extract user embeddings from DeepFM? I don't know how to do that, since the paper didn't provide such method.

**Comment by tanmaygovil1999-sharechat** [comment]
Okay Okay

**Comment by tanmaygovil1999-sharechat** [comment]
And If I have a very huge dataset then how can I train DeepFM with split of that dataset ?
