### ISSUE TITLE
Error while retraining model

### ISSUE THREAD

**Issue by ckay016** [massquantity/LibRecommender#145]
Unable to retrain a model using the saved model and data info.
Followed all the steps mentioned in examples/model_retrain_examples.py

## Trained a new Item2Vec model and save the data_info and model.
data_info.save("models","data_info")
base_model.save("models", "cur_model", manual=True, inference_only=False)

## Loaded old data info
old_data_info = DataInfo.load("models","data_info")

## Initialised the new Item2Vec model
new_model = Item2Vec(
    "ranking",
    data_info,
    embed_size=16,
    norm_embed=False,
    window_size=3,
    n_epochs=10,
    n_threads=0,
)

## Trying to rebuild model as shown in examples/model_retrain_example.py
new_model.rebuild_model(path="models", model_name="cur_model", full_assign=True)

AttributeError: 'Item2Vec' object has no attribute 'rebuild_model'

I've gone through the library and it indeed seems like there is not rebuild_model or rebuild_tf_model attribute associated with the model. Should I be loading the model in any other way instead?

**Comment by massquantity** [comment]
For now retraining only supports tensorflow and torch models, but item2vec is implemented using Gensim. I'm not very familiar with Gensim, so I need some time to find out whether the gensim models can load the old embedding and retrain with new data. If everything goes well we may be able to retrain item2vec model in the next version.

**Comment by massquantity** [comment]
Retraining Item2Vec should work now!
