### ISSUE TITLE
Tensor Shape Error when Implementing DatasetFeat

### ISSUE THREAD

**Issue by Harsh-2420** [massquantity/LibRecommender#149]
The library works fine for the DatasetPure section (using only user data). But when I try to add more data in DatasetFeat, there's a wrong Tensor shape error. 

```python
train_data, eval_data = random_split(trainData, test_size=0.2)


## The 4 lists below don't include columns - user, item and label. In total, the data has 17 features
sparse_col = [ ... ]  # 11 column names
dense_col = [ ... ]  # 3 column names
user_col = [ ... ] # 9  column names
item_col = [ ... ]  # 5 column names

train_data, data_info = DatasetFeat.build_trainset(
    train_data, user_col, item_col, sparse_col, dense_col
)
eval_data = DatasetFeat.build_testset(eval_data)

train_data.build_negative_samples(
    data_info, item_gen_mode="random", num_neg=1, seed=2020
)
eval_data.build_negative_samples(
    data_info, item_gen_mode="random", num_neg=1, seed=2222
)



metrics = [
    "loss",
    "balanced_accuracy",
    "roc_auc",
    "pr_auc",
    "precision",
    "recall",
    "map",
    "ndcg",
]

reset_state("DeepFM")
deepfm = DeepFM(
    "ranking",
    data_info,
    loss_type="cross_entropy",
    embed_size=16,
    n_epochs=2,
    lr=1e-4,
    lr_decay=False,
    reg=None,
    batch_size=2048,
    num_neg=1,
    use_bn=False,
    dropout_rate=None,
    hidden_units="128,64,32",
    tf_sess_config=None,
)
deepfm.fit(
    train_data,
    verbose=2,
    shuffle=True,
    eval_data=eval_data,
    metrics=metrics,
)
print("prediction: ", deepfm.predict(user=1, item=2333))
print("recommendation: ", deepfm.recommend_user(user=1, n_rec=7))

```

### The Error:

`Cannot feed value of shape (858, 10) for Tensor 'Placeholder_3:0', which has shape '(?, 11)'`

_I can't provide data or column names since it's confidential but I can try my best to clear any questions you have_

**Comment by massquantity** [comment]
The problem is that you specified 11 sparse columns, but the transformed data only has 10. You can `print(train_data.sparse_indices.shape)` after `DatasetFeat.build_trainset`  to check the real shape of the transformed data.
If it indeed only has 10 sparse columns, you can add the 11 sparse columns one by one to see which column actually caused the problem, and don't forget to modify the corresponding `user_col` or `item_col`.

**Comment by Harsh-2420** [comment]
`train_data.sparse_indices.shape` gives me a shape with 11 sparse columns.

**Comment by massquantity** [comment]
Then the most probable cause is these column names. Use `print(train_data.sparse_indices.shape)` AFTER `train_data.build_negative_samples` to check the shape of sampled data.
Also `print(dict(data_info.col_name_mapping))` to check the internal column information. It should contains keys `sparse_col`, `user_sparse_col`, `item_sparse_col`. 
Make sure `len(data_info.col_name_mapping["user_sparse_col"]) + len(data_info.col_name_mapping["item_sparse_col"])` equals `len(data_info.col_name_mapping["sparse_col"])`

**Comment by Harsh-2420** [comment]
got it. one of the columns were being removed on negative sampling. Any idea why that happens?

Also, I had another question - how does the recommend_user work? In the examples, it says als.recommend_user()user=1, n_rec=7)). Is the user=1 referring to index or to userid=1. If its the latter and my data doesnt have userid=1, does it default to cold start?
And if it uses user index, how is it sorted (or does it use the same order i passed the data in)?
