### ISSUE TITLE
AssertionError: common size doesn't match...

### ISSUE THREAD

**Issue by Sade-KD** [massquantity/LibRecommender#15]
The following error occurs when the dataset is increased to 2 million rows and epoch is increased above 15 using the Youtube Model Ranking model.
Traceback (most recent call last):
  File "momentum_feat_main_awsV5_pt2.py", line 203, in <module>
    "recall", "map", "ndcg"])
  File "/home/ubuntu/anaconda3/envs/Rec_Models/lib/python3.6/site-packages/libreco/algorithms/youtube_ranking.py", line 242, in fit
    self.print_metrics(eval_data=eval_data, metrics=metrics)
  File "/home/ubuntu/anaconda3/envs/Rec_Models/lib/python3.6/site-packages/libreco/evaluate/evaluate.py", line 155, in print_metrics
    self.df=print_metrics_ranking(self.df,metrics, **test_params, k=k, train=False)
  File "/home/ubuntu/anaconda3/envs/Rec_Models/lib/python3.6/site-packages/libreco/evaluate/evaluate.py", line 279, in print_metrics_ranking
    map_all = map_at_k(y_true_list, y_reco_list, users, k)
  File "/home/ubuntu/anaconda3/envs/Rec_Models/lib/python3.6/site-packages/libreco/evaluate/metrics.py", line 56, in map_at_k
    map_all.append(average_precision_at_k(y_true, y_reco, k))
  File "/home/ubuntu/anaconda3/envs/Rec_Models/lib/python3.6/site-packages/libreco/evaluate/metrics.py", line 45, in average_precision_at_k
    assert len(ap) == common_items.size, "common size doesn't match..."
AssertionError: common size doesn't match...
(Rec_Models) ubuntu@ip-10-248-9-50:~/Projects/RecommendationModel/LibRec/main$

![error](https://user-images.githubusercontent.com/42578613/96415496-fd084b80-11ee-11eb-9a1c-8737f7c44e47.PNG)

In most cases, a re-run or decreasing the epoch under 10 will reduce the occurrence of the error.

The parameters are set as follows:
```
     ytb_ranking = YouTubeRanking(task="ranking", data_info=data_info,
                                    embed_size=16, n_epochs=4, lr=1e-4, #0.01
                                    batch_size=512, use_bn=True,
                                    hidden_units="128,64,32")
    

     ytb_ranking.fit(train_data, verbose=2, shuffle=True,
                      eval_data=test_data,
                      metrics=["loss", "roc_auc", "precision","recall"
                               , "map", "ndcg"])
```

**Comment by massquantity** [comment]
I think the reason is that some users may have consumed an item for more than once, and the `np.intersect1d` function is set to `assume_unique=True`. You can simply remove the `assert` line in `evaluate/metrics.py` and give it a try:
```python
def average_precision_at_k(y_true, y_reco, k):
    common_items, indices_in_true, indices_in_reco = np.intersect1d(
        y_true, y_reco, assume_unique=True, return_indices=True)

    rank_list = np.zeros(k)
    if common_items.size > 0:
        rank_list[indices_in_reco] = 1
        ap = [np.mean(rank_list[:i+1]) for i in range(k) if rank_list[i]]
        assert len(ap) == common_items.size, "common size doesn't match..."   # remove this line
        return np.mean(ap)
    else:
        return 0
```

**Comment by Sade-KD** [comment]
I think the reason for this is that people may have cancelled and re subscribed. I will test this and check the data again, and updated the post.
