### ISSUE TITLE
detect unkown user Error

### ISSUE THREAD

**Issue by Harsh-2420** [massquantity/LibRecommender#167]
After training and fitting the model, every userID gives the error "detect unkown user".

The docs show ```model.data_info.user2id ``` which is a dictionary of 

```python 
original_ids : new_ids
```

Neither the original nor new ID gives any result. It keeps defaulting to cold_start recommendations.

the code has ```model.data_info.user2id.get(userID, -1) ```. Any user that's input here will return -1

**Comment by massquantity** [comment]
Your expression confuses me. Unless `model.data_info.user2id` is empty, no way every userID inputs in it returns -1.
If it's not empty, at least keys inside `user2id` will not return -1. But you said every userID has "detect unkown user", which means every userID is not key of `user2id`.

One more thing, you did not change the `inner_id` parameter in `recommend_user` function, right?

**Comment by Harsh-2420** [comment]
I tried the same code in another machine and it worked. For some reason the library didn't seem to work on my old machine. Thanks!
