### ISSUE TITLE
ItemCF & UserCF bugs in recommend_user method.

### ISSUE THREAD

**Issue by mxhyxym** [massquantity/LibRecommender#169]
**ItemCF.recommend_user**
`user_id = self._check_unknown_user(user, inner_id)`
because _check_unknown_user return an inner_id of user, thus the following user should use user_id instead:
```
u_consumed = set(self.user_consumed[user])
user_slice = slice(self.user_interaction.indptr[user], 
                   self.user_interaction.indptr[user + 1]) 
```
so do **UserCF.recommend_user**:
```
user_slice = slice(self.sim_matrix.indptr[user],
                     self.sim_matrix.indptr[user + 1])

k_nbs_and_sims = self.topk_sim[user]
```

**Comment by mxhyxym** [comment]
**ItemCF.recommend_user**
when the `len(result) == 0`, should not use `self.data_info.popular_items[:n_rec]` for the cold start, because it returns the inner_id of items, you can use `self.popular_recommends(inner_id, n_rec)` which consider the condition of `inner_id=False`.

so do **UserCF.recommend_user** when `sim_users.size == 0`

**Comment by mxhyxym** [comment]
In **ItemCF.recommend_user** and **UserCF.recommend_user**, when `inner_id=False`, it should not be return the inner_id of items, the origin names of items are better, I think.

Some code like:
```
if not inner_id:
    rank_items = [(self.data_info.id2item[i[0]], i[1]) for i in rank_items]
```

**Comment by massquantity** [comment]
Yes you are quite right. These will be fixed in the next version.
