### ISSUE TITLE
 ERROR: Failed building wheel for LibRecommender

### ISSUE THREAD

**Issue by retecata** [massquantity/LibRecommender#20]
Hi, I've tried installing this library with pip and I keep running into some errors. Could you please point me in the right direction?
   
cl : Command line error D8021 : invalid numeric argument '/Wno-unused-function'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

ERROR: Command errored out with exit status 1: 'c:\python64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Kat\\AppData\\Local\\Temp\\pip-install-znh68all\\librecommender\\setup.py'"'"'; __file__='"'"'C:\\Users\\Kat\\AppData\\Local\\Temp\\pip-install-znh68all\\librecommender\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Kat\AppData\Local\Temp\pip-record-56rkh6f3\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python64\Include\LibRecommender' Check the logs for full command output.

I tried installing from source too.

**Comment by massquantity** [comment]
I think the reason is that your system is Windows, and maybe there are some compatibility problems with it. Have you installed Cython when building from source?   
The final workaround is download all the code and cd into the folder, then maybe you can use it directly.

**Comment by Shadz13** [comment]
The error message 
`error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x64\cl.exe' failed with exit status 2`
is related to a complier issue. Please ensure nvcc version is the same as the cuda version, ensure that you are using the correct version of visual studio etc. and lastly check nvida paths.

I have list some suggestions below to detecting the error:
nvcc --version
nvidia-smi
conda list cudatoolkit
conda list cudnn

print(tf_build_info.cuda_version_number)
# 9.0 in v1.10.0
print(tf_build_info.cudnn_version_number)
# 7 in v1.10.0

Check if cuda is recognised
conda install -c msys2 m2w64-gcc
numba -s
https://github.com/numba/numba/issues/3840

**Comment by retecata** [comment]
Hi guys, thank you for your replies! It's true I am using Windows so the issue is most likely with my system setup. Thank you for the suggestions! I ended up doing something else so I don't require this library anymore, but I will try your suggestions if I come back at it! I will close the issue now, thanks for the help again!
