### ISSUE TITLE
Questions about refitting a trained model on new data + GPU training

### ISSUE THREAD

**Issue by YahyaL** [massquantity/LibRecommender#25]
Thanks for this great library. I love how it is easy to use and all the features that it contains.

I have 2 separate questions :

1. How can I use this library if I want to refit new interactions with new users and new items without having to retrain from scratch ? More specifically how can I handle building a new TransformedSet that keeps the same indices as the TransformedSet used for the initial training of the model and adding new indices for unseen users, items or sparse features? 
2. How can I use a GPU for training the deep learning models available ?

Thanks again !

**Comment by massquantity** [comment]
1. Currently the library doesn't support adding new users and items without retraining. I have to say it will take a lot of work to achieve this, so maybe some day:)
2. According to the tf doc, tensorflow will detect and use a GPU automatically if you have one.

**Comment by massquantity** [comment]
Problem of retraining with new users/items was solved in version `0.6.0`.
