### ISSUE TITLE
Recommendations for unknown user id in serving

### ISSUE THREAD

**Issue by jaya-shankar** [massquantity/LibRecommender#276]
Hey 👋,

The library is fantastic! 👏, It made my work a lot easier in trying and testing different model

My issue is  I want to know if there is any way to get a recommendation for a new user (cold start) based on the user's recent purchases in the serving phase

Apparently, I have trained and saved the YouTubeRanking model. After going through the [documentation](https://librecommender.readthedocs.io/en/latest/serving_guide/python.html) I got the model for serving

<img width="400" alt="Screenshot 2023-04-23 at 2 29 39 AM" src="https://user-images.githubusercontent.com/44873355/233806408-dd1c5e6c-e691-4036-ab7c-af71d6aa100e.png">

And I am looking if is possible to make a request as follows

<img width="399" alt="Screenshot 2023-04-23 at 2 31 22 AM" src="https://user-images.githubusercontent.com/44873355/233806462-2eb66340-5ad6-4af4-a3d3-779a40b70029.png">

where _user_id:1_ is a new user and was not part of the training data and _seq_ is a list of products purchased by user_id 1

I could get some recommendations for the unknown users, in the testing phase and want to know how can I get them in the serving phase.

**Comment by massquantity** [comment]
Hi, 
Sequence recommendation is a relatively new feature in this library and has not been supported in the serving phase. But it's in the plan.
Right now, the only way is to write your own service by using frameworks such as Flask and Sanic :grinning:.
