### ISSUE TITLE
NGCF load is not working 

### ISSUE THREAD

**Issue by Hwismos** [massquantity/LibRecommender#283]
Hi there, I have a question about loading saved model.

I saved NGCF model and tried to load it. But I am getting the error. 

`
FileNotFoundError: [Errno 2] No such file or directory: 'model_path/NGCF.npz'
`

I checked `libreco/bases/embed_base.py`, and I found `load` method implemented like this, `variable_path = os.path.join(path, f"{model_name}.npz")`. But I don't have .npz file, instead I have .pt file.

**Comment by massquantity** [comment]
Yeah I know, the save/load part is a bit confusing in LibRecommender.

As the [Save/Load Model](https://librecommender.readthedocs.io/en/latest/user_guide/evaluation_save_load.html#save-load-model) doc suggests, saving the model is used for inference or retraining. The inference mode will only save the embeddings in numpy `npz` format, and the retraining mode will save the torch variables in `pt` format. 

I don't know about your intention, but maybe you should set `inference_only=True` in the `save` method.

**Comment by Hwismos** [comment]
It works thank you. 

My intention was to inference with saved model. I did `inference_only=False` before.
