### ISSUE TITLE
re ranking a list of item ids

### ISSUE THREAD

**Issue by vyaslkv** [massquantity/LibRecommender#318]
How can we re rank the list of item ids for a particular user. I have trained a YT ranking model.

**Comment by massquantity** [comment]
Can you provide more information on the criteria used for the reranking?

**Comment by vyaslkv** [comment]
data_info = DataInfo.load("/", model_name="YT_model")
ytb_ranking = YouTubeRanking.load(
    path="/", model_name="YT_model", data_info=data_info, manual=True
)

in the below code 
ytb_ranking.predict(user=[722436],item=[148348])
we can pass only one item id not multiple item ids to predict the score
not like 
ytb_ranking.predict(user=[722436],item=[148348,142134])
the above won't work

**Comment by massquantity** [comment]
The [predict](https://librecommender.readthedocs.io/en/latest/api/algorithms/youtube_ranking.html#libreco.algorithms.YouTubeRanking.predict) method accepts a batch of ids, so u can just duplicate the user id and get multiple prediction scores:

```python
ytb_ranking.predict(user=[722436, 722436], item=[148348, 142134])
```

**Comment by vyaslkv** [comment]
Thanks, solved!!
