### ISSUE TITLE
Colab GPU not speeding up the PinSage training 

### ISSUE THREAD

**Issue by NomanSaleem4** [massquantity/LibRecommender#328]
Hi, I am training the PinSage on the colab GPU but it's not speeding up the training, rather training on my local machine is faster than on the colab. Any reason or suggestion for speeding up the training? Thanks

**Comment by massquantity** [comment]
PinSage requires heavy CPU data loading since it needs to sample nodes from all neighbors, but the CPUs in Colab are weak, and it only has two cores.

You can use the DGL version, i.e., PinSageDGL, which is much faster. But make sure you install the CUDA version of DGL.

**Comment by NomanSaleem4** [comment]
ok. 
Can you please list what should be the specs of the GPUs to have a multiprocessing?
Thanks
