### ISSUE TITLE
Initializer ValueError with basic ranking model

### ISSUE THREAD

**Issue by ddofer** [massquantity/LibRecommender#33]
I'm trying to run the youTubeRanking model. 

ValueError: The initializer passed is not valid. It should be a callable with no arguments and the shape should not be provided or an instance of `tf.keras.initializers.*' and `shape` should be fully defined.

I get the following errors:

random neg item sampling elapsed: 0.084s
random neg item sampling elapsed: 0.002s
n_users: 9058, n_items: 456, data sparsity: 0.8459 %
Training start time: 2021-01-05 21:56:53
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-938e3c81fdee> in <module>
     29 ytb_ranking.fit(train_data, verbose=1, shuffle=True,
     30                 eval_data=test_data,
---> 31                 metrics=[ "precision","recall"])

[....]
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, constraint, synchronization, aggregation)
    541           constraint=constraint,
    542           synchronization=synchronization,
--> 543           aggregation=aggregation)
    544 
    545     synchronization, aggregation, trainable = (

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint, synchronization, aggregation)
    938           variable_dtype = None
    939         else:
--> 940           raise ValueError("The initializer passed is not valid. It should "
    941                            "be a callable with no arguments and the "
    942                            "shape should not be provided or an instance of "

**ValueError: The initializer passed is not valid. It should be a callable with no arguments and the shape should not be provided or an instance of `tf.keras.initializers.*' and `shape` should be fully defined.**
```

My data input code looks like this (I have a mix of sparse numeric and string features): 

`train_data, test_data = split_by_ratio_chrono(df, test_size=0.1)

# specify complete columns information
sparse_col = ['country',   'booker']
dense_col = []
user_col = ["user"]
item_col = ["item"] 

train_data, data_info = DatasetFeat.build_trainset(
    train_data, user_col, item_col, sparse_col, dense_col
)
test_data = DatasetFeat.build_testset(test_data)

# sample negative items for each record
train_data.build_negative_samples(data_info,num_neg=4)
test_data.build_negative_samples(data_info)

## 
ytb_ranking = YouTubeRanking (task="ranking", data_info=data_info,
                             embed_size=16, n_epochs=3, lr=1e-4,
                             batch_size=256, use_bn=True,
                             hidden_units="128,64,32")
ytb_ranking.fit(train_data, verbose=1, shuffle=True,
                eval_data=test_data,
                metrics=[ "precision","recall"]) `

Thanks!

**Comment by ddofer** [comment]
The same error occurs when  Itry running the quickstart movielens example from the readme/main page: (I copy pasted it + changed the data dir);

`C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint, synchronization, aggregation)
    891         tb = [x for x in tb if "tensorflow/python" not in x[0]][:5]
    892         raise ValueError("%s Originally defined at:\n\n%s" %
--> 893                          (err_msg, "".join(traceback.format_list(tb))))
    894       found_var = self._vars[name]
    895       if not shape.is_compatible_with(found_var.get_shape()):

ValueError: Variable user_features already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 1752, in variable_v2
    shared_name=shared_name, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\state_ops.py", line 79, in variable_op_v2
    shared_name=shared_name)`

**Comment by ddofer** [comment]
Update: Figured it out, I was providing the user column as a user feature and item column to items. (I misunderstood how it is meant to be used, and thought that those were for specifying the columns). 
It's working now, albeit surprisingly poorly (very very slow, especially in the negative sampling generation stage, and the final youtube ranking model underperforms a lightFM model with pure CF. The data is sparse - only ~4 interactions per user. n_users: 162904, n_items: 3667, data sparsity: 0.0977 % ) .

It might help to update the documentation/variable name on this point!

**Comment by massquantity** [comment]
Thanks for your advice. I'm curious about the speed. How much time does it take to do negative sampling and how many instances do you have?
