### ISSUE TITLE
Simple Loading of the You Tube Recommendation Model

### ISSUE THREAD

**Issue by Shadz13** [massquantity/LibRecommender#35]
I have read through the readme which contains a load using flask. I am currently saving the model as such https://github.com/massquantity/LibRecommender/issues/10#issuecomment-707470504 
```
>>> from libreco.utils import save_info, save_model_tf_serving
>>> ytb_ranking = YouTubeRanking(...)
>>> ytb_ranking.fit(...)  # train model
>>> path = "tf_model"  # specify model saving directory
>>> save_model_tf_serving(path, ytb_ranking, "youtube")  # save tf model
```

and would like to know if there is a simple way to this model without deploying with the flask?

At the moment, Im using the following code:
```
frozen_graph_filename='C:\\Projects\\RecommendationModel\\data\\rec_data_mainfeat_alldeepFM_0\\1\\saved_model.pb'

with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

graph = tf.get_default_graph()
tf.import_graph_def(graph_def, name="prefix")
```

However, it results in the following error: 
```
    graph_def.ParseFromString(f.read())

DecodeError: Error parsing message
```

**Comment by Shadz13** [comment]
I am to have resolved the issue using the following code:

```
import tensorflow as tf
import sys
from tensorflow.python.platform import gfile
from tensorflow.core.protobuf import saved_model_pb2
from tensorflow.python.util import compat

with tf.Session() as sess:
    model_filename ='C:\\Projects\\RecommendationModel\\data\\rec_data_mainfeat_alldeepFM_0\\1\\saved_model.pb'
    with gfile.FastGFile(model_filename, 'rb') as f:
        data = compat.as_bytes(f.read())
        sm = saved_model_pb2.SavedModel()
        sm.ParseFromString(data)
        g_in = tf.import_graph_def(sm.meta_graphs[0].graph_def)
```

**Comment by massquantity** [comment]
I have seen a lot of ways about saving and loading TensorFlow models on the internet. Honestly I'm also confused right now because some are about tf1 and some are about tf2. I haven't tested it yet, but you can try the [tf.saved_model.loader](https://tensorflow.google.cn/versions/r1.15/api_docs/python/tf/saved_model/loader) API.

I decide to do some research and add some methods to solve this save/load problem. But it will take a few days.

**Comment by Shadz13** [comment]
```
path ="C:\\Recommendation\\"
model_name="modelname"
version=1       
export_dir = os.path.join(path, f"{model_name}/{version}")
with tf.compat.v1.Session(graph=tf.Graph()) as sess:
  tf.compat.v1.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], export_dir)
```

**Comment by Shadz13** [comment]
I am trying to adjust the code to predict the resulted from the loaded model.

This is an example to obtain the final node when the input is x. How can the code be adjusted to obtained the prediction results for each user:
    x = graph.get_tensor_by_name("x:0")
    model = graph.get_tensor_by_name("finalnode:0")
    print(sess.run(model, {x: [5, 6, 7, 8]}))

Currently this is the code used for prediction:
```
    def recommend_user(self, user, n_rec, **kwargs):
        user = self._check_unknown_user(user)
        if not user:
            return  # popular ?

        (user_indices,
         item_indices,
         sparse_indices,
         dense_values) = get_recommend_indices_and_values(
            self.data_info, user, self.n_items, self.sparse, self.dense)
        feed_dict = self._get_feed_dict(user_indices, item_indices,
                                        sparse_indices, dense_values,
                                        None, False)

        recos = self.sess.run(self.output, feed_dict)
        if self.task == "ranking":
            recos = 1 / (1 + np.exp(-recos))

        consumed = self.user_consumed[user]
        count = n_rec + len(consumed)
        ids = np.argpartition(recos, -count)[-count:]
        rank = sorted(zip(ids, recos[ids]), key=lambda x: -x[1])
        return list(
            islice(
                (rec for rec in rank if rec[0] not in consumed), n_rec
            )
        )

```
To obtain predicted results I use the following:
     for i in range( 1,1000):
         t=auto_int_best.recommend_user(user=i, n_rec=7)

**Comment by massquantity** [comment]
1. I'm still working on the model save/load problem. It's not that so easy since it will affect the library's current code structure.
2. I think the **Predict API** that article mentioned is an API inside TensorFlow Serving, because I couldn't find this predict API in normal TensorFlow.
3. This library mainly supports the fixed data scenario, which assumes the features will not change. The point you made totally made sense, and click data changes rapidly everyday. So since you've asked, I'm also trying to figure out a way on how to  handle that.

**Comment by Shadz13** [comment]
Thank you so much. I am learning so much about the library and recommendation as a whole.

In addition to point 3, Would the model not become more flexible if it is not dependent on the client id? Is the deep FM model both and item based and user based model? I may have been under assumption that all feature based models are item based models.

**Comment by massquantity** [comment]
DeepFM is a rather flexible model. Basically you can choose to include whatever features you want, by not including client id is an option.

**Comment by massquantity** [comment]
I've released a new version `0.4.0`, which can do some simple model saving and loading, see this example [script](https://github.com/massquantity/LibRecommender/blob/master/examples/save_load_example.py).
Also note that in this version there is no need to do indices mapping as in this [issue](https://github.com/massquantity/LibRecommender/issues/12). 
Now the `predict` and `recommend_user` function can accept original ids. 
```python
>>> model.predict(1, 110)
>>> model.recommend_user(1, 7))
>>> model.predict(1, 110, inner_id=True)  # by specifying inner_id will use the library's converted id.
```

**Comment by Shadz13** [comment]
Thanks, does the new version 0.4.0 accept new/updated features ?

**Comment by massquantity** [comment]
No, it doesn't. I've come up with some ideas about it, and maybe they can be implemented in the next version.
