### ISSUE TITLE
user_consumed contain negative items not just positive items 

### ISSUE THREAD

**Issue by uusama** [massquantity/LibRecommender#364]
I'm building a ranking RS my label is Implicit but I can obtain the negative samples my self

so my label contains zeros & ones.
I got a really high precision score and upon investigation i found that 'user_consumed' in eval data contains the item from positive labels and negative ones.

the code for how i create the sets:

"""
train_data, data_info = DatasetFeat.build_trainset(
    train_df, user_col, item_col, sparse_cols, dense_col
)
eval_data = DatasetFeat.build_testset(eval_df)
"""

My dataframes contains label(0 or 1), item, user, time, other user & item features.

Is there's something I'm missing? or there's a workaround?

**Comment by uusama** [comment]
As a work around I selected the rows in my eval where label is 1 
and duplicated them but with label =0 
so in model evaluation only the items that was truly one is available in user_consumer
& rows with zero exists to avoid throwing errors

**Comment by massquantity** [comment]
Hi, this is indeed a bug. We only considered the case when the eval data only contains positive samples.

The workaround is constructing the `user_consumed` by excluding the negative samples:
```python
eval_data = DatasetFeat.build_testset(eval_df)

from collections import defaultdict

def get_user_consumed(data):
    user_consumed = defaultdict(list)
    for u, i, lb in zip(data.user_indices, data.item_indices, data.labels):
        if lb == 1:
            # convert np.int to int
            if isinstance(u, np.integer):
                u = u.item()
            if isinstance(i, np.integer):
                i = i.item()
            user_consumed[u].append(i)
    # remove possible duplicated items
    return {u: np.unique(items).tolist() for u, items in user_consumed.items()}

new_user_consumed = get_user_consumed(eval_data)
eval_data.user_consumed = new_user_consumed
```

**Comment by massquantity** [comment]
As a reminder, since you can obtain the negative samples, don't forget to set `neg_sampling=False` in the `fit()` and `evaluate()` functions.
