### ISSUE TITLE
Ranking of interactions when using the "ranking" for implicit data

### ISSUE THREAD

**Issue by noman-git** [massquantity/LibRecommender#381]
Hi, so I have read the docs where it says that the label in implicit data can be arbitrary since all the data is regarded as positive samples. In the movie rating dataset example you have turned the ratings to labels. In the same way I have created a label -> priority column to rank my interactions. I have some questions regarding that.

1) Does having or not having that column affect my output in anyway. (Imagine the data not being filtered in any way after this, only more columns are added which should not change our original premise here).

![image](https://github.com/massquantity/LibRecommender/assets/96649476/fe1596ac-f626-43f0-a7b9-b1dd9f9d7a1f)

2) If the "priority" does not affect the output, then how can I give more priority to my items as given in the data above so the output is in accordance with that. What I am doing right now is grouping my data and if one item has triggered multiple events (InCart, purchased), then I only select the highest priority one (purchased according to the above data). Does that happen to get the result I want since my positive samples would usually contain more of the data I am giving priority to.

Edit: The column name is "label" when I actually give it to the model, This was just in the intermediate step.

**Comment by massquantity** [comment]
1. Hi, the priority column doesn't affect the output since they will all be converted to 1 when being treated as labels.
2. Did you mean that not all samples have a "priority" value in your data? You need to do some data preprocessing in pandas to filter out the low priority samples you don't want. For example,

```python
df = pd.DataFrame({
    "item":[1, 1, 1, 1, 1, 2, 2], 
    "event_type": ["purchased", "cart", "purchased", "removed", "cart", "removed", "cart"], 
    "priority": [5, 3, 5, 1, 3, 1, 3]}
)

---------------------------------

   item event_type  priority
0     1  purchased         5
1     1       cart         3
2     1  purchased         5
3     1    removed         1
4     1       cart         3
5     2    removed         1
6     2       cart         3

---------------------------------

def filter_based_on_priority(data: pd.DataFrame):
    highest_priority = data["priority"].max()
    return data[data["priority"] == highest_priority]

df.groupby("item").apply(filter_based_on_priority).reset_index(drop=True)

---------------------------------

   item event_type  priority
0     1  purchased         5
1     1  purchased         5
2     2       cart         3
```

**Comment by noman-git** [comment]
The first question has been cleared. Thank you for that.
The second one however is not what I asked.

My end goal is to achieve the recommendations based on the priority I assign to the **_"event_type"_**. I do not want all of them to be passed as **1** to the model. How should I go about that problem. 
1) Should I go for a **rating** model and use the priorities as rating or is that a bad Idea in this case?
2) Is there some model for ranking that can incorporate this?
3) If it is possible to use some kind of weighted loss in GraphSage that will get this result, then how will it be incorporated besides just defining it in the **_loss.py_** file.
I am open to any other suggestins as well. Cheers :)

**Comment by massquantity** [comment]
Well, you can try the "rating" task. But I don't think it's a good idea since the model may treat "InCart" samples as negative samples.

In general, samples with weights are not supported in this library. To achieve this a lot of source codes have to be changed, especially the data loading part.

**Comment by noman-git** [comment]
Great, Thank you. I'll try to see what I can do with the source code. I'm closing this issue. Cheers.
