### ISSUE TITLE
Error when running `logloss` evaluation from sklearn

### ISSUE THREAD

**Issue by jpzhangvincent** [massquantity/LibRecommender#390]
It seems the root cause is the sklearn logloss evaluation metric function. Any quick workaround?
<img width="841" alt="Screenshot 2023-10-24 at 9 20 42 AM" src="https://github.com/massquantity/LibRecommender/assets/7220686/ed4400c2-1f45-4bd1-ae7e-b1961be66f03">

**Comment by massquantity** [comment]
Yeah, either check if your data contains missing values or avoid using the `loss` metric.
