### ISSUE TITLE
Getting embeddings from Fm model

### ISSUE THREAD

**Issue by skylersky** [massquantity/LibRecommender#391]
hi all, 
It there a way to getting embeddings from the FM function? like 'fm.get_item_embedding()' ?

**Comment by skylersky** [comment]
i think i figure it out.  FM itself  has a save() function where could save the model to .npz file. Then i read the file back and slice, that's how i get the embeddings. Correct me if i was wrong.

**Comment by massquantity** [comment]
Hi, if your data doesn't use other features, i.e. sparse or dense features, this approach is feasible. However, it would be challenging to get embeddings from FM when features are included since features are merged together.
