### ISSUE TITLE
Improvement of Speed for DatasetFeat class in Version 0.6.0

### ISSUE THREAD

**Issue by Shadz13** [massquantity/LibRecommender#42]
Version : 0.6.0
Number of samples: 1,2 million
Number of items: 38
Machine Type: AWS -Deep AMI which is similar to EC2

I was currently using version 1.0.0,  the data generation process and training completed in approx, 4 hours. When I, updated the model version 6.0.0,  line `train_data, data_info = DatasetFeat.build_trainset(train_data_main, user_colm, item_colm, sparse_colm, dense_colm)` takes over 12 hours to run and still has not completed.

When I investigated further I noticed that the code was only utilizing one CPU and not being processed on multiple CPUs, which resulted in a slower run.

Is there a way to ensure that the library runs on multiple CPUs --> a quick work around then updating the library code completely?

**Comment by massquantity** [comment]
I was shocked by the speed...  It takes less than 5 minutes to process and train a model in my laptop with 10 million data. 
Are you sure the code got stuck in line `train_data, data_info = DatasetFeat.build_trainset`? Since you only have 38 items, I'm guessing maybe the negative sampling line became slow:
```train_data.build_negative_samples(data_info)```

**Comment by Shadz13** [comment]
Me as well. I tested it on a smaller subset of the dataset of 10k unique clients and it ran really quickly. I am abit worried since it is running of AWS and I am trying identify the problem. 

I have placed prints to notify where in the code it is and the code has not completed train_data, data_info = DatasetFeat.build_trainset(train_data_main, user_colm, item_colm, sparse_colm, dense_colm). 

Currently, I did a re-run and its been running for 2 hrs and 49 mins.
Below is the htop results:
![htop](https://user-images.githubusercontent.com/42578613/108773979-c6a95700-7567-11eb-8cb5-d316e3589609.PNG)

Kindly note that I did update the following in the code from our previous discussion (I am not sure if this affects the new version, however the 10k dataset ran fine):

# def sample_item_with_tolerance(num, consumed_items, consumed_len, tolerance=5):
#     assert num > tolerance
#     sampled = []
#     first_len = num - tolerance
#     while len(sampled) < first_len:
#         i = floor(random() * consumed_len)
#         if consumed_items[i] not in sampled:
#             sampled.append(consumed_items[i])
#     for _ in range(tolerance):
#         i = floor(random() * consumed_len)
#         sampled.append(consumed_items[i])
#     return sampled

**def sample_item_with_tolerance(num, consumed_items, consumed_len, tolerance=5):
    sampled = []
    for _ in range(num):
        i = floor(random() * consumed_len)
        sampled.append(consumed_items[i])
    return sampled**

**Comment by massquantity** [comment]
My suggestion is placing prints inside the function `build_trainset` in `libreco/data/dataset.py`, then you can identify which line took the longest time. Below I place 11 prints, start from line 445:

```python
cls._set_feature_col(sparse_col, dense_col, multi_sparse_col)
print(1)  ##########################
cls._set_sparse_unique_vals(train_data)
print(2)   ##########################

if shuffle:
    train_data = train_data.sample(
        frac=1, random_state=seed
    ).reset_index(drop=True)

user_indices, item_indices = get_user_item_sparse_indices(
    train_data, cls.user_unique_vals, cls.item_unique_vals,
    mode="train", ordered=True
)
print(3)   ##########################
train_sparse_indices = (
    merge_sparse_indices(
        cls, train_data, cls.sparse_col,
        cls.multi_sparse_col, mode="train",
        ordered=True
    )
    if cls.sparse_col or cls.multi_sparse_col
    else None
)
print(4)
train_dense_values = (
    train_data[cls.dense_col].to_numpy()
    if cls.dense_col
    else None
)
labels = train_data["label"].to_numpy(dtype=np.float32)

train_transformed = TransformedSet(user_indices,
                                    item_indices,
                                    labels,
                                    train_sparse_indices,
                                    train_dense_values,
                                    train=True)
print(5)
all_sparse_col = (
    merge_sparse_col(cls.sparse_col, cls.multi_sparse_col)
    if cls.multi_sparse_col
    else sparse_col
)
print(6)
col_name_mapping = col_name2index(
    user_col, item_col, all_sparse_col, cls.dense_col
)
user_sparse_col_indices = list(
    col_name_mapping["user_sparse_col"].values()
)
user_dense_col_indices = list(
    col_name_mapping["user_dense_col"].values()
)
item_sparse_col_indices = list(
    col_name_mapping["item_sparse_col"].values()
)
item_dense_col_indices = list(
    col_name_mapping["item_dense_col"].values()
)

(
    user_sparse_unique,
    user_dense_unique,
    item_sparse_unique,
    item_dense_unique
) = construct_unique_feat(user_indices,
                            item_indices,
                            train_sparse_indices,
                            train_dense_values,
                            user_sparse_col_indices,
                            user_dense_col_indices,
                            item_sparse_col_indices,
                            item_dense_col_indices)
print(7)
sparse_offset = (
    merge_offset(cls, cls.sparse_col, cls.multi_sparse_col)
    if cls.sparse_col or cls.multi_sparse_col
    else None
)
print(8)
sparse_unique_vals = (
    dict(**cls.sparse_unique_vals, **cls.multi_sparse_unique_vals)
    if cls.sparse_col or cls.multi_sparse_col
    else None
)
print(9)
sparse_oov = (
    get_oov_pos(cls, sparse_col, multi_sparse_col)
    if cls.sparse_col or cls.multi_sparse_col
    else None
)
print(10)
interaction_data = train_data[["user", "item", "label"]]
data_info = DataInfo(col_name_mapping,
                        interaction_data,
                        user_sparse_unique,
                        user_dense_unique,
                        item_sparse_unique,
                        item_dense_unique,
                        user_indices,
                        item_indices,
                        cls.user_unique_vals,
                        cls.item_unique_vals,
                        sparse_unique_vals,
                        sparse_offset,
                        sparse_oov)
print(11)
cls.train_called = True
return train_transformed, data_info
```

**Comment by Shadz13** [comment]
Right at the beginning of the run, it stated in white : "always remove parenthesis assert("

It hangs at print 10
![bug](https://user-images.githubusercontent.com/42578613/108816561-0d766b80-75bf-11eb-825d-68d0faa0a66f.PNG)

**Comment by Shadz13** [comment]
When I ran the new dataset script on the local machine, I get the following error:
```
Traceback (most recent call last):

  File "C:\Projects\RecommendationModel\LibRecommender-master\LibRec\main\TrainingScript_LocalMachine_2.py", line 198, in <module>
    train_data, data_info = DatasetFeat.build_trainset(train_data_main, user_colm, item_colm, sparse_colm, dense_colm)

  File "C:\Anaconda3\envs\rec_v4\lib\site-packages\libreco\data\dataset.py", line 380, in build_trainset
    cls._check_subclass()

  File "C:\Anaconda3\envs\rec_v4\lib\site-packages\libreco\data\dataset.py", line 63, in _check_subclass
    "Please use 'DatasetPure' or 'DatasetFeat' to call method"

NameError: Please use 'DatasetPure' or 'DatasetFeat' to call method
```

**Comment by massquantity** [comment]
> The code hangs at print 10
> ![bug](https://user-images.githubusercontent.com/42578613/108816561-0d766b80-75bf-11eb-825d-68d0faa0a66f.PNG)

I guess it's the two pandas functions that make the code slow. Try this code on your original data and see if it is slow:
```python
count_items = data.drop_duplicates(subset=["user", "item"]).groupby("item")["user"].count()
```

**Comment by Shadz13** [comment]
train_data_main=train_data_main.drop(feat_dropm, axis=1)
             train_data_main=train_data_main.drop_duplicates()
             print('train_data_main prev shape :',train_data_main.shape)
             
             test_data_main=test_data_main.drop(feat_dropm, axis=1)
             test_data_main=test_data_main.drop_duplicates()   
             
             print('Users unique',len( train_data_main.user.unique()))
             print('item unique', len(train_data_main.item.unique()))
             
             print('features dropped ===> ', feat_dropm)
             print('Training featues ===> ', train_data_main.columns)
             
  ##################################################### Updated Request Below:
             count_items = train_data_main.drop_duplicates(subset=["user", "item"]).groupby("item")["user"].count()
             train_data_main = train_data_main.drop_duplicates(subset=["user", "item"])
             print('train_data_main shape :',train_data_main.shape)


![count_item](https://user-images.githubusercontent.com/42578613/108827972-ea53b800-75ce-11eb-8ee3-9aec5675bb2f.PNG)

Results of the shape previously is the same:
train_data_main prev shape : (1178968, 15)
train_data_main shape : (1178968, 15)

**Comment by massquantity** [comment]
Since the code hang on `data_info = DataInfo(...)`, you can test its constructor in four place in `libreco/data/data_info.py`:
```python
class DataInfo(object):
    def __init__(
            self,
            col_name_mapping=None,
            interaction_data=None,
            user_sparse_unique=None,
            user_dense_unique=None,
            item_sparse_unique=None,
            item_dense_unique=None,
            user_indices=None,
            item_indices=None,
            user_unique_vals=None,
            item_unique_vals=None,
            sparse_unique_vals=None,
            sparse_offset=None,
            sparse_oov=None,
    ):
        self.col_name_mapping = col_name_mapping
        self.interaction_data = interaction_data
        self.user_sparse_unique = user_sparse_unique
        self.user_dense_unique = user_dense_unique
        self.item_sparse_unique = item_sparse_unique
        self.item_dense_unique = item_dense_unique
        self.user_consumed, self.item_consumed = interaction_consumed(
            user_indices, item_indices
        )
        print(1) ###
        self.user_unique_vals = user_unique_vals
        self.item_unique_vals = item_unique_vals
        self.sparse_unique_vals = sparse_unique_vals
        self.sparse_unique_idxs = self.map_unique_vals(sparse_unique_vals)
        print(2)  ###
        self.sparse_offset = sparse_offset
        self.sparse_oov = sparse_oov
        self._n_users = None
        self._n_items = None
        self._user2id = None
        self._item2id = None
        self._id2user = None
        self._id2item = None
        self._data_size = None
        self.popular_items = None
        # store old sparse len and oov
        self.old_sparse_len = None
        self.old_sparse_oov = None
        self.all_args = locals()
        self.add_oov()
        print(3)  ###
        if self.popular_items is None:
            self.set_popular_items(100)
            print(4)  ####
```

**Comment by Shadz13** [comment]
I removed the new features, I added to the dataset in user and sparse list:
![data](https://user-images.githubusercontent.com/42578613/108832041-a1523280-75d3-11eb-9a06-9c46a9c499ad.PNG)

I need to add in the features one at a time to see which one is causing the problem and the reason its occurring.

In addition, I printed out the parameters passed through ```
DataInfo(col_name_mapping,
                                    interaction_data,
                                    user_sparse_unique,
                                    user_dense_unique,
                                    item_sparse_unique,
                                    item_dense_unique,
                                    user_indices,
                                    item_indices,
                                    cls.user_unique_vals,
                                    cls.item_unique_vals,
                                    sparse_unique_vals,
                                    sparse_offset,
                                    sparse_oov)
```
1) Is this correct --> item_sparse_unique:  None
2) And can time be a label to a feature in the user and sparse list? -The reason I asked this is because we used it previously for chronological split algorithm and maybe its not allowed to be reused elsewhere.

**Comment by massquantity** [comment]
1. It is correct if you have no item sparse features.
2. Theoretically time can be used as a feature.

**Comment by Shadz13** [comment]
Login_occurrence that is resulting a extremely slow run. 

The array  passed to DataInfo above contains the following:  'Login_ocurrence': array([ 1.,  2.,  3., ..., nan, nan, nan] .Its type is float64.

**Comment by massquantity** [comment]
What are the original values of Login_occurrence? The passed array belongs to which argument of DataInfo, `user_sparse_unique` or `cls.user_unique_vals`?

**Comment by Shadz13** [comment]
1) What are the original values of Login_occurrence? 
`unique_logins =train_data_main.Login_ocurrence.unique()`

![logins](https://user-images.githubusercontent.com/42578613/108841546-9c47b000-75e0-11eb-8301-0254aa2a0e74.PNG)
![logins2](https://user-images.githubusercontent.com/42578613/108841581-a7024500-75e0-11eb-88ea-8a4f7de2a926.PNG)

2) The passed array belongs to which argument of DataInfo, user_sparse_unique or cls.user_unique_vals?
The array mentioned above is under sparse_unique_vals
```
For user_sparse_unique:  [[    1    10    14 ...  8724  8786 14682]
 [    1     8    15 ...  8724  9172  9345]
 [    0     9    14 ...  8724  8786 14682]
 ...
 [    0    11    15 ...  8724  8786 14682]
 [    1     8    14 ...  8724  8786 14682]
 [    1     7    14 ...  8724  8786 14682]]
```

`For cls.user_unique_vals:  [    140     149     160 ... 7625974 7626030 7626099]`

**Comment by Shadz13** [comment]
Resolved on local machine
```
     train_data_main['Login_ocurrence'] = train_data_main['Login_ocurrence'].fillna(-1).astype(np.int64)
     test_data_main['Login_ocurrence'] = test_data_main['Login_ocurrence'].fillna(-1).astype(np.int64)
     train_data_main.loc[train_data_main['Login_ocurrence'] == -1,'Login_ocurrence'] = np.nan
     test_data_main.loc[test_data_main['Login_ocurrence'] == -1,'Login_ocurrence'] = np.nan

```
![resolved](https://user-images.githubusercontent.com/42578613/108845633-54c42280-75e6-11eb-936d-cc0f97ac650d.PNG)

**Comment by Shadz13** [comment]
Apologies the problem is still persisting. It is resolved only under this conditions.
     train_data_main['Login_ocurrence'] = train_data_main['Login_ocurrence'].fillna(0).astype(np.int64)
     test_data_main['Login_ocurrence'] = test_data_main['Login_ocurrence'].fillna(0).astype(np.int64)

When I added in the nans, the issue continued:
     train_data_main.loc[train_data_main['Login_ocurrence'] == -1,'Login_ocurrence'] = np.nan
     test_data_main.loc[test_data_main['Login_ocurrence'] == -1,'Login_ocurrence'] = np.nan

**Comment by massquantity** [comment]
I forgot to mention that nans are not allowed in data, and you must fill in with some value. 

Also I noticed that there is a value using scientific notation, `8.2422e+06`. The code inside the library applies `np.unique()` to every sparse feature, and this value will make numpy treat the feature as float64. It is necessary to convert it to int64 as you do. You can try yourself to see what is going on.

```python
np.unique([8.2422e6, 1, 2, np.nan, np.nan])
np.unique([8.2422e6, 1, 2, np.nan, np.nan]).dtype
np.unique([8.2422e6, 1, 2]).dtype
```
