### ISSUE TITLE
Logging DeepFM Model

### ISSUE THREAD

**Issue by ManishaNumtra** [massquantity/LibRecommender#442]
Hi
While logging models of deepFM. We are unable to save a pb file. Due to which we are unable to further load the model for predictions. Could you please help us on how to log the model using tensorflow.

**Comment by massquantity** [comment]
Please provide all your code here.

**Comment by massquantity** [comment]
Why not use the [official API](https://librecommender.readthedocs.io/en/latest/api/algorithms/deepfm.html#libreco.algorithms.DeepFM.load) to load the model?

The [source code](https://github.com/massquantity/LibRecommender/blob/master/libreco/utils/save_load.py#L51) uses `tf.train.Saver` to save the model, so I assume this is the direct tensorflow way? 

I've seen the [source code](https://mlflow.org/docs/latest/_modules/mlflow/tensorflow.html#autolog) in mlflow on logging model, and I don't think it is compatible with models in this library.

**Comment by ManishaNumtra** [comment]
Hi
Thank you for the support. I found a solution using mlflow.pyfunc to log as a customized model and could log and load the model for predictions.
