### ISSUE TITLE
Can't instantiate abstract class UserCF with abstract methods load, save

### ISSUE THREAD

**Issue by Jazzpenner** [massquantity/LibRecommender#49]
Hey,
 I'am getting this error trying to use a UserCf-RS. 

`user_cf = UserCF(task="rating", data_info=data_info, k=20, sim_type="cosine")`

leads to

`Can't instantiate abstract class UserCF with abstract methods load, save`

Happens with Python 3.6.12. But actually - after trying out several Python versions - I'am not able to figure out one, where building and UserCF is working together (or when exactly the behavior of Abstract Classes was changed?). Actually I'm not able to fix this problem. 

Is there an easy solution? 
Greetings

**Comment by massquantity** [comment]
Yeah sure, I think there are some bugs in UserCF's implementation. I'll fix them in a few days, thanks.

**Comment by Jazzpenner** [comment]
Same problem pops up with the ItemCF-Implementation. Anyway, thanks a lot for the library and your work.

**Comment by massquantity** [comment]
Fixed in version `0.6.4`. It turns out that I forgot to implement the abstract method `save` and `load` from the base class.

**Comment by Jazzpenner** [comment]
Well, thanks a lot. It works now!
