### ISSUE TITLE
ValueError: The `YouTuBeRetrieval` model assumes no item features.

### ISSUE THREAD

**Issue by BhaveshBhansali** [massquantity/LibRecommender#493]
I am trying to pass item and user column. However, YouTuBeRetrieval throws following error:
![Uploading Screenshot 2024-06-19 at 09.16.16.png…]()

    136 assert task == "ranking", "YouTube-type models is only suitable for ranking"
    137 if len(data_info.item_col) > 0:
--> 138     raise ValueError("The `YouTuBeRetrieval` model assumes no item features.")
    139 self.all_args = locals()
    140 self.loss_type = loss_type

ValueError: The `YouTuBeRetrieval` model assumes no item features.

**Comment by massquantity** [comment]
According to the paper, the `YouTuBeRetrieval` model doesn't use item features, so you should set item features to an empty list. See [example](https://github.com/massquantity/LibRecommender/blob/master/examples/feat_ranking_example.py#L409).
