### ISSUE TITLE
Source code of 'recommend_user' API

### ISSUE THREAD

**Issue by BhaveshBhansali** [massquantity/LibRecommender#496]
I would like to access model.recommend_user API. May I have link of it?

**Comment by massquantity** [comment]
`model.recommend_user` mainly inherits from the [base classes](https://librecommender.readthedocs.io/en/latest/api/algorithms/bases.html), and different models have different base classes. For example, the [DeepFM doc](https://librecommender.readthedocs.io/en/latest/api/algorithms/deepfm.html) indicates the base class is `TfBase`, so the link is https://github.com/massquantity/LibRecommender/blob/master/libreco/bases/tf_base.py#L186

**Comment by BhaveshBhansali** [comment]
Thank you for the link.
