### ISSUE TITLE
Failed installation of LibRecommender=0.6.4

### ISSUE THREAD

**Issue by anuliketat** [massquantity/LibRecommender#51]
Hi, please help me install and use this library. It failed building wheel for the library. Please look at the attached images of the error.
![Screenshot (31)](https://user-images.githubusercontent.com/11734945/116147789-c2cbb980-a6fd-11eb-983f-704013703d68.png)
![Screenshot (32)](https://user-images.githubusercontent.com/11734945/116147795-c3fce680-a6fd-11eb-9d0a-82a8da763186.png)

**Comment by massquantity** [comment]
It looks like the compiler is mingw, and we're expecting visual c++. You can install visual c++ first.
Or if you don't want to install it, you can clone the whole library and cd into `LibRecommender` folder, then you can import the library directly.
