### ISSUE TITLE
Recommender Systems just predicts expected value

### ISSUE THREAD

**Issue by AlexVaith** [massquantity/LibRecommender#59]
I am struggling to use the models. I have a custom dataset, that has high sparsity --> n_users: 9026, n_items: 37, data sparsity: 6.2205 %

Every model I have tried with and without additional features just learns to predict the expected value. Am I doing something wrong?

**Comment by AlexVaith** [comment]
all values are very close to the global mean rating. the r2 metrics confirms that intuition by outputting a value of 0

**Comment by massquantity** [comment]
What's the range of your label, like 1 to 5?

**Comment by AlexVaith** [comment]
yes, but the ratings are all very high and the ratings are floats not integers

**Comment by massquantity** [comment]
Really no idea, unless you show some data examples.
