### ISSUE TITLE
algorithm gets stucked after negative sampling

### ISSUE THREAD

**Issue by sorushsaghari** [massquantity/LibRecommender#65]
Hi.
I'm using youtube ranking. when I use random sampling, calling model. fit doesn't make any progress.
![image](https://user-images.githubusercontent.com/38028950/124909792-1e6cca00-e000-11eb-8a2e-435dd3804ac0.png)
```python
reset_state("YouTubeRanking")
ytb_ranking = YouTubeRanking("ranking", data_info, embed_size=16, n_epochs=10,
                             lr=.00003, lr_decay=1e-4, reg=None, batch_size=1024,
                             num_neg=1, use_bn=False, dropout_rate=None,
                             hidden_units="265,128,64,64,32",)
ytb_ranking.fit(train_data, verbose=2, shuffle=True, eval_data=eval_data,
                recent_num=None, sample_rate=None,
                metrics=["loss"])
```
and this is my dataset :
![image](https://user-images.githubusercontent.com/38028950/124910162-87544200-e000-11eb-8c3d-fb8f8dc558e3.png)

**Comment by massquantity** [comment]
Please provide all your code here, and how many data, users and items do you have?

**Comment by sorushsaghari** [comment]
```python
import numpy as np
import pandas as pd
from libreco.data import  DatasetFeat, random_split
import tensorflow as tf
from libreco.algorithms import YouTubeRanking  # feat data, algorithm YouTubeRanking

train_df = pd.read_csv("train_ids_games.csv", sep=",", header=0)
columns_titles = ["user", "item", "label", "brand",
                  "verified", "vote", "emb1", "emb2", "emb3", "emb4", "emb5"]
train_df = train_df.reindex(columns=columns_titles)
train_df['label'] = train_df['label'].map(lambda label: 1 if label > 3.7 else 0)

sparse_col = ["brand", "verified"]
dense_col = ["emb1", "emb2", "emb3", "emb4", "emb5", "vote"]
user_col = ["verified", "vote"]
item_col = ["brand", "emb1", "emb2", "emb3", "emb4", "emb5"]

train_data, eval_data = random_split(
    train_df.dropna(), multi_ratios=[0.8, 0.1])
train_data, data_info = DatasetFeat.build_trainset(
    train_df.dropna(), user_col, item_col, sparse_col, dense_col
)
eval_data = DatasetFeat.build_testset(eval_data)
train_data.build_negative_samples(data_info, item_gen_mode="random",
                                    num_neg=1, seed=2020)
eval_data.build_negative_samples(data_info, item_gen_mode="random",
                                    num_neg=1, seed=2222)

def reset_state(name):
    tf.compat.v1.reset_default_graph()
    print("\n", "=" * 30, name, "=" * 30)


reset_state("YouTubeRanking")
ytb_ranking = YouTubeRanking("ranking", data_info, embed_size=16, n_epochs=10,
                                lr=1e-4, lr_decay=1e-5, reg=None, batch_size=2048,
                                num_neg=0, use_bn=True, dropout_rate=.4,
                                hidden_units="128,64,32", tf_sess_config=None)
ytb_ranking.fit(train_data, verbose=2, shuffle=True, eval_data=eval_data,
                recent_num=None, sample_rate=None,
                metrics=["loss"])
```
`n_users: 55197, n_items: 17259, data sparsity: 0.0389 %`
![image](https://user-images.githubusercontent.com/38028950/125047777-8c72c900-e0b4-11eb-8e9a-277cca92298b.png)

**Comment by massquantity** [comment]
What do you mean by getting stuck? The progress bar doesn't move at all? Have you tried using other algoithms?
I can see three problems in your code.

1. Since you treat label > 3.7 as 1 and <= 3.7 as 0, no need to do negative sampling explicitly. You can remove these two lines:
```python
train_data.build_negative_samples(data_info, item_gen_mode="random",
                                    num_neg=1, seed=2020)
eval_data.build_negative_samples(data_info, item_gen_mode="random",
                                    num_neg=1, seed=2222)
```

2. You still use `train_df.dropna()` in `DatasetFeat.build_trainset`, which should be `train_data`.

3. `lr_decay` value is too low. The typical range is 0.8 - 0.999.

**Comment by massquantity** [comment]
It's the [pandas reindex](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html) problem. This line `train_df = train_df.reindex(columns=columns_titles)` will make all data become NaNs. 
You should use `train_df.columns = columns_titles` to assign column names.

**Comment by sorushsaghari** [comment]
yes sure this is a sample : 
https://drive.google.com/file/d/14hk_ccasc9OpCakloP9LZzHe1gXB7-hs/view?usp=sharing

**Comment by SohumBhatt** [comment]
Apologies for reviving this, I was having the same issue of DIN and YoutubeRanking having no progress when training. But I solved it by changing the size of my training and test set. Is it possible that the issue comes from the splitting of the dataset? Both DIN and YoutubeRanking use sequence for recommendation, so maybe that is where the issue comes from?

**Comment by massquantity** [comment]
It's an issue from negative sampling, which should've been solved in the latest library version:)
