### ISSUE TITLE
ALS 

### ISSUE THREAD

**Issue by neenerrh** [massquantity/LibRecommender#66]
Implementing the ranking task bt got the following error

name 'als_update' is not defined

**Comment by massquantity** [comment]
What's your os? Have you installed Cython first?

**Comment by neenerrh** [comment]
I installed it though I am using google colab

**Comment by massquantity** [comment]
I also tested in colab, but this problem didn't occur. Did wheel successfully built during installing? 

<img width="1119" alt="Screen Shot 2021-07-14 at 23 26 49" src="https://user-images.githubusercontent.com/28751760/125649284-771018ef-e3d2-4f65-8da6-a9ecd14f8054.png">

**Comment by Xuey99** [comment]
Hello, I have the same problem.
```
Similarity cython version is not available
ALS cython version is not available
BPR cython version is not available
```
But BPR algorithm runs noemally, ALS can't run.
`name 'als_update' is not defined`
If you find a solution, can you share it? Thank you!

**Comment by sunithak** [comment]
Any solution to this cython problem? I am stuck at same problem

**Comment by massquantity** [comment]
The problem should've been solved in the latest version :)
