### ISSUE TITLE
tf.zeros vs tf.keras.Initializers.zeros

### ISSUE THREAD

**Issue by apdullahyayik** [massquantity/LibRecommender#75]
At the implementation of "Personalized Top-N Sequential Recommendation via Convolutional Sequence Embedding" in `algorithm/cesar.py`, I have encountered a bug due to initializers. Here, I am reporting it and suggesting a solution.

When initializing bias vectors at `algorithm/cesar.py/_build_variables` method, initialization for zeros is set with `tf.zeros`.

![image](https://user-images.githubusercontent.com/5982905/128639341-4983e60e-8b1b-496c-b5a2-403ee89e746a.png)

However by tensorflow team, for tf.1.14 and over, initialization at `varaible_scope.py` below, operations are written with assumption of having "partition_info" argument. Which is only available when using tf.keras.Initalizers.zeros is used.

![image](https://user-images.githubusercontent.com/5982905/128639463-03e61fa2-478c-42a2-9630-4ae405af0805.png)

![image](https://user-images.githubusercontent.com/5982905/128639475-c4c5768c-eca8-4550-ba4d-0c1e029ace2b.png)

So the `_build_variables` method should be like these:

```Python
def _build_variables(self):
  self.user_feat = tf.get_variable(
      name="user_feat",
      shape=[self.n_users, self.embed_size],
      initializer=tf_truncated_normal(0.0, 0.01),
      regularizer=self.reg)

  # weight and bias parameters for last fc_layer
  self.item_biases = tf.get_variable(
      name="item_biases",
      shape=[self.n_items],
      initializer=tf.keras.initializers.zeros,
  )

  self.item_weights = tf.get_variable(
      name="item_weights",
      shape=[self.n_items, self.embed_size * 2],
      initializer=tf_truncated_normal(0.0, 0.02),
      regularizer=self.reg
  )

  # input_embed for cnn_layer, include padding value
  self.input_embed = tf.get_variable(
      name="input_embed",
      shape=[self.n_items + 1, self.embed_size],
      initializer=tf_glorot_normal,
      regularizer=self.reg
  )
```

**Comment by massquantity** [comment]
Yeah, I've used `tf.keras.initializers.zeros` in other algorithms, but forgot to use it in `caser.py`. I'll fix it, or you could fire a PR.

By the way, what does `parition_info` do in initializers?

**Comment by apdullahyayik** [comment]
Thanks for this intuitive library. Actually, I don’t know what partition
info at zeros is. Be sure that I will send a PR shortly.


By the way I have encountered a problem when using Cesar model at ranking
stage. I have reported it here

https://github.com/massquantity/LibRecommender/issues/48#issuecomment-895066669

Can you suggest a solution?

**Comment by massquantity** [comment]
I'll reply in that issue. I'm also curious that does `caser` offer a good performance on your data?

**Comment by apdullahyayik** [comment]
I  have adapted data ans created model but  could have trained due to the
reported error, but I think it will. I am looking forward to see your
reply.
