### ISSUE TITLE
failed installation on Windows, python 3.6, cython 0.29.0

### ISSUE THREAD

**Issue by WingController** [massquantity/LibRecommender#76]
Hi, Im installing the package with [pip install LibRecommender==0.6.10]，but failed. I need help, Thank you so much ! :)

![image](https://user-images.githubusercontent.com/10721368/129318278-44d2c46a-c4aa-4c00-a7ec-90b83a39e1ce.png)

**Comment by massquantity** [comment]
Really, it is difficult to deal with Windows problems...  My cython version is 0.29.23, so maybe you can try this version ?
Another solution is cloning all the code and cd into the LibRecommender folder. Then maybe you can use the library directly.
Final solution is installing and using the library in Google Colab.

**Comment by WingController** [comment]
> Really, it is difficult to deal with Windows problems... My cython version is 0.29.23, so maybe you can try installing this version first? Another solution is cloning all the code and cd into the LibRecommender folder. Then maybe you can use the library directly. The final solution is installing and using the library in Google Colab.

Thank you.
