### ISSUE TITLE
Running the same algorithm multiple times?

### ISSUE THREAD

**Issue by lukas-wegmeth** [massquantity/LibRecommender#93]
I would like to run an algorithm like SVDpp multiple times in a single run. However, Tensorflow throws an exception on starting the second run, stating that the variables can not be created because they already exist. I wasn't able to reset them without changing library source code. Is there a simpler way to do this?

**Comment by massquantity** [comment]
Refer to this issue, #26

**Comment by lukas-wegmeth** [comment]
I did precisely this before, but it throws an exception.

`ValueError: Fetch argument <tf.Operation 'init' type=NoOp> cannot be interpreted as a Tensor. (Operation name: "init"
op: "NoOp"
input: "^bu_var/Assign"
input: "^bi_var/Assign"
input: "^pu_var/Assign"
input: "^qi_var/Assign"
input: "^yj_var/Assign"
input: "^beta1_power/Assign"
input: "^beta2_power/Assign"
input: "^bu_var/Adam/Assign"
input: "^bu_var/Adam_1/Assign"
input: "^bi_var/Adam/Assign"
input: "^bi_var/Adam_1/Assign"
input: "^pu_var/Adam/Assign"
input: "^pu_var/Adam_1/Assign"
input: "^qi_var/Adam/Assign"
input: "^qi_var/Adam_1/Assign"
input: "^yj_var/Adam/Assign"
input: "^yj_var/Adam_1/Assign"
 is not an element of this graph.)

Process finished with exit code 1
`

Tested with Python 3.9, TF 2.8 + 2.5, Numpy 1.22.2 + 1.19.5 on Windows 10.

**Comment by massquantity** [comment]
I also tested on this, but no problem occurs. I'm using Python 3.8, TF 2.5, Numpy 1.22.2 on MacOS, so maybe it's a Windows problem.

**Comment by lukas-wegmeth** [comment]
I am going to test this on Linux next then. I will report back once I have the results. Thanks for your assistance!
